--Insert some cites
INSERT INTO cities VALUES
('NYC', 'New York City', 'USA'),
('TYO', 'Tokyo', 'JPN'),
('LON', 'London', 'GBR'),
('PEK', 'Beijing', 'CHN'),
('PAR', 'Paris', 'FRA'),
('BER', 'Berlin', 'DEU'),
('SYD', 'Sydney', 'AUS'),
('YTO', 'Toronto', 'CAN'),
('BKK', 'Bangkok', 'THA'),
('IST', 'Istanbul', 'TUR'),
('JNB', 'Johannesburg', 'ZAF'),
('SIN', 'Singapore', 'SGP'),
('DUB', 'Dublin', 'IRL'),
('MEX', 'Mexico City', 'MEX'),
('DEL', 'Delhi', 'IND'),
('ZRH', 'Zurich', 'CHE'),
('SEL', 'Seoul', 'KOR'),
('HKG', 'Hong Kong', 'HKG'),
('HAN', 'Hanoi', 'VNM'),
('LAX', 'Los Angeles', 'USA'),
('OSA', 'Osaka', 'JPN'),
('MAN', 'Manchester', 'GBR'),
('SHA', 'Shanghai', 'CHN'),
('CDG', 'Paris Charles de Gaulle', 'FRA'),
('MUC', 'Munich', 'DEU'),
('MEL', 'Melbourne', 'AUS'),
('YVR', 'Vancouver', 'CAN'),
('BNE', 'Brisbane', 'AUS'),
('HCM', 'Ho Chi Minh City', 'VNM'),
('DAD', 'Da Nang City', 'VNM');
